app_url: http://localhost:3000
app_name: NFT
app_logo: logo.png
base_coin: ETH
app_coin: WETH
auto_approval: true
secret_key_base: b2d96dac611f4a65c84e5c85d16ec9cf90ddd88795d0a57a4fb207745dc9f81a0b4aa336f375dc5bfefb002ca72ba5164b645eb17c566cb5cceb7207d0b1c397
ethereum_provider: https://ropsten.infura.io/v3/17def5988a254395a0570477c141050c
signer_private_key: dfafasfaf #Do not keep currencies to this address
coingecko_url: https://api.coingecko.com/api/v3/simple/price
contract_address:
  erc721: '0x428791F08ed8E555192C566b512A73df3b0b06FA'
auto_approval: true
etherscan:
  api_key: MG9UWFS674HWGIRM37QGSEVSDQJ6FRUJ6Z
  api_url: https://api-rinkeby.etherscan.io/api
pinata:
  api_key: 718736c6aa6fe1b70e40
  api_secret: 911b1e3afd6177be7f1db08cde5069b957ad1a8530cd36cb28ab69615ff7da9e
  base_url: https://api.pinata.cloud/pinning/pinFileToIPFS
default_fees:
  service_fee: 2.5
discussion_url: https://govnft.bafdemo.com
support_url: https://faqnft.bafdemo.com
send_email: false # Send email or not
mailer_address: 'smtp.gmail.com' # Enter the server address for your SMTP server
mailer_port: 587 # Enter the port of your SMTP server
mailer_username: smtp_username # Enter your SMTP email username
mailer_password: smtp_password # Enter your SMTP email password
tls_auto: true
exception_sender: inbound.support@yourdomain.com # Enter your exception sender email
exception_recipients: ['support@yourdomain.com'] # Enter your exception recipients email
email_prefix: '[NFT] ' # Enter your exception email prefix
